# Orb 'circleci/hello-build@0.0.5' resolved to 'circleci/hello-build@0.0.5'
version: 2.1

executors:
  masonite-orb:
    parameters:
      CIRCLE_TOKEN: 
        type: string
        default: $CIRCLE_TOKEN
    docker:
      - image: masoniteproject/orb:latest 
      
jobs:
  trigger:
    parameters:
      repo:
        type: string
        default: 'masoniteframework/api'
      branch:
        type: string
        default: master
    executor: masonite-orb
    steps:
    - run:
        command: python /trigger_build.py --repo << parameters.repo >> --branch << parameters.branch >>